### PR TITLE
Added certificate management class

### PR DESCRIPTION
**Pull request by Woody1193**
This PR adds certificate management to the repostiory.

### CODE REVIEW

**Comment by Woody1193** [comment]
Task linked: [CU-8693z3etc MMS API library MVP complete](https://app.clickup.com/t/8693z3etc)

**Review by Liam-Woods — COMMENTED** [review]
Shouldn't certs be stored in secrets manager, and retrieved using py-shared?

**Comment by Woody1193** [comment]
@Liam-Woods That is the intent for the service that consumes this library, but this is intended to be open-sourced and we don't want the public knowing how we store our certificates. Plus, they wouldn't be able to download the `py-shared` dependency. That being said, I forgot that you had included the ability to edit the `requests.session` with those so I might remove this code.

**Comment by Liam-Woods** [comment]
I forgot this is open source! Ignore me.

**Review by Liam-Woods — APPROVED** [review]

**Pull request merged**
